#ifndef _KEY_H_
#define _KEY_H_

#if defined( IIC_Key_Board_LCD) && (defined (EPSON_LCD))
#define PANEL_LED_ADDR_POWERON      PANEL_LED_ADDR_BUSY
#define PANEL_LED_BIT_POWERON       PANEL_LED_BIT_BUSY

#define PANEL_LED_ADDR_BUSY        0x10
#define PANEL_LED_ADDR_HEAT_PRE     0x11
#define PANEL_LED_ADDR_HEAT_MIDDLE  0x12
#define PANEL_LED_ADDR_HEAT_POST    0x13

#define PANEL_LED_BIT_BUSY         0x0
#define PANEL_LED_BIT_HEAT_PRE     0x1
#define PANEL_LED_BIT_HEAT_MIDDLE  0x2
#define PANEL_LED_BIT_HEAT_POST    0x3

#define PANEL_LED_ADDR_DATATRANSFER 0x11
#define PANEL_LED_ADDR_CLEAN_WEAK   0x12
#define PANEL_LED_ADDR_CLEAN_NORMAL 0x13
#define PANEL_LED_ADDR_CLEAN_STRONG 0x14
#define PANEL_LED_ADDR_HEADLEVEL_HIGH 0x10
#define PANEL_LED_ADDR_HEADLEVEL_LOW  0x17
#define PANEL_LED_ADDR_QUALITY_ON   0x15
#define PANEL_LED_ADDR_QUALITY_OFF  0x16

#define PANEL_LED_BIT_DATATRANSFER 0x1
#define PANEL_LED_BIT_CLEAN_WEAK   0x2
#define PANEL_LED_BIT_CLEAN_NORMAL 0x3
#define PANEL_LED_BIT_CLEAN_STRONG 0x4
#define PANEL_LED_BIT_HEADLEVEL_HIGH 0x0
#define PANEL_LED_BIT_HEADLEVEL_LOW  0x7
#define PANEL_LED_BIT_QUALITY_ON   0x5
#define PANEL_LED_BIT_QUALITY_OFF  0x6

#if defined(EPSON_BOTTOM_BOARD_V2) || defined(EPSON_BOTTOM_BOARD_V2_1) || defined(EPSON_BOTTOM_BOARD_V3)

#if defined(MANUFACTURER_DYSS)||defined(MANUFACTURER_ADDTOP_EPSON)||defined(LCD_BOARD_B_VERSION)
//#if 0
#define PANEL_KEY_ID_LEFT   2  
#define PANEL_KEY_ID_RIGHT  9  
#define PANEL_KEY_ID_UP     1  
#define PANEL_KEY_ID_DOWN   10 
#define PANEL_KEY_ID_MENU   41
#define PANEL_KEY_ID_ENTER  58
#define PANEL_KEY_ID_CANCEL 25  
#define PANEL_KEY_ID_PAUSE  34  
#define PANEL_KEY_ID_CLEAN  26  
#define PANEL_KEY_ID_BASEPOINT    42
#define PANEL_KEY_ID_SHEETCUT     50  
#define PANEL_KEY_ID_PRINTQUALITY 17  
#define PANEL_KEY_ID_CHECKNOZZLE  18  
#define PANEL_KEY_ID_HEATER  33  

#else
#define PANEL_KEY_ID_LEFT   2  
#define PANEL_KEY_ID_RIGHT  9  
#define PANEL_KEY_ID_UP     1  
#define PANEL_KEY_ID_DOWN   10 
#define PANEL_KEY_ID_MENU   49
#define PANEL_KEY_ID_ENTER  50
#define PANEL_KEY_ID_CANCEL 25  
#define PANEL_KEY_ID_PAUSE  34  
#define PANEL_KEY_ID_CLEAN  26  
//micolor special:
#define PANEL_KEY_ID_BASEPOINT    42
#define PANEL_KEY_ID_SHEETCUT     41  // ADVANCE MODE	
#define PANEL_KEY_ID_PRINTQUALITY 17  // MEDIA TYPE
//Allwin Special:
#define PANEL_KEY_ID_CHECKNOZZLE  18  
//Qicaihong Special:
#define PANEL_KEY_ID_HEATER  33  
#endif
#else

#define PANEL_KEY_ID_LEFT   58  //SW16
#define PANEL_KEY_ID_RIGHT  10   //SW10
#define PANEL_KEY_ID_UP     18  //SW4
#define PANEL_KEY_ID_DOWN   17  //SW3
#define PANEL_KEY_ID_MENU   33  //SW5
#define PANEL_KEY_ID_ENTER  25  //SW11
#define PANEL_KEY_ID_CANCEL  9  //SW9
#define PANEL_KEY_ID_PAUSE  26  //SW12
#define PANEL_KEY_ID_CLEAN  57  //SW15
//micolor special:
#define PANEL_KEY_ID_BASEPOINT    49  //SW7
#define PANEL_KEY_ID_SHEETCUT     50  //SW8
#define PANEL_KEY_ID_PRINTQUALITY 41  //SW13
//Allwin Special:
#define PANEL_KEY_ID_CHECKNOZZLE  34  //SW6
#endif

#else

#define GET_KEY_STATE()  ((PIO_GET_RAW(&PGKeyPins)) >> 15)

#define KEYBITS 0xF7F

#define KEY_SHIFT_PURGE 5
#define KEY_SHIFT_ESC	6 //?
#define KEY_SHIFT_PAUSE 4
#define KEY_SHIFT_UP	2 //?
#define KEY_SHIFT_DOWN  3
#define KEY_SHIFT_LEFT	0
#define KEY_SHIFT_RIGHT 1

#define KEY_SHIFT_CYAN  	8
#define KEY_SHIFT_MAGENTA 	9
#define KEY_SHIFT_YELLOW	10
#define KEY_SHIFT_BLACK		11


#define KEY_BIT_PURGE	(0x001<<KEY_SHIFT_PURGE)
#define KEY_BIT_ESC		(0x001<<KEY_SHIFT_ESC)
#define KEY_BIT_PAUSE	(0x001<<KEY_SHIFT_PAUSE)
#define KEY_BIT_UP		(0x001<<KEY_SHIFT_UP)
#define KEY_BIT_DOWN	(0x001<<KEY_SHIFT_DOWN)
#define KEY_BIT_LEFT	(0x001<<KEY_SHIFT_LEFT)
#define KEY_BIT_RIGHT	(0x001<<KEY_SHIFT_RIGHT)

#define KEY_BIT_CYAN	(0x001<<KEY_SHIFT_CYAN)
#define KEY_BIT_MAGENTA (0x001<<KEY_SHIFT_MAGENTA)
#define KEY_BIT_YELLOW	(0x001<<KEY_SHIFT_YELLOW)
#define KEY_BIT_BLACK	(0x001<<KEY_SHIFT_BLACK)

#define KEY_COMPOSE_PLUS	0x80 
#define KEY_UP_PLUS			0x100
#define KEY_LONGPUSH_PLUS	0x200


#if 0
#define KEY_MOVE_LEFT		3
#define KEY_MOVE_RIGHT		4
#define KEY_MOVE_UP			1
#define KEY_MOVE_DOWN 		2
#define KEY_PAUSE_RESUME	16
#define KEY_CANCEL_REQ		15
#define KEY_AUTOCLEAN		14
#define KEY_PURGE			12		
#define KEY_PURGE_ESC		13
#define KEY_CLEAN_SINGLE_1	5
#define KEY_CLEAN_SINGLE_2	6
#define KEY_CLEAN_SINGLE_3	7
#define KEY_CLEAN_SINGLE_4	8
#define KEY_CLEAN_SINGLE_5	9
#define KEY_CLEAN_SINGLE_6	10
#else
#define KEY_MOVE_LEFT		KEY_SHIFT_LEFT
#define KEY_MOVE_RIGHT		KEY_SHIFT_RIGHT
#define KEY_MOVE_UP			KEY_SHIFT_UP
#define KEY_MOVE_DOWN 		KEY_SHIFT_DOWN
#define KEY_PAUSE_RESUME	KEY_SHIFT_PAUSE
#define KEY_CANCEL_REQ		KEY_COMPOSE_PLUS
#define KEY_AUTOCLEAN		KEY_SHIFT_PURGE+KEY_UP_PLUS
#define KEY_PURGE			KEY_SHIFT_PURGE+KEY_LONGPUSH_PLUS
#define KEY_PURGE_ESC		KEY_SHIFT_ESC+KEY_UP_PLUS

//#define KEY_CLEAN_SINGLE_1	(KEY_COMPOSE_PLUS+1)
//#define KEY_CLEAN_SINGLE_2	(KEY_COMPOSE_PLUS+2)
#define KEY_CLEAN_SINGLE_3	KEY_SHIFT_BLACK
#define KEY_CLEAN_SINGLE_4	KEY_SHIFT_YELLOW
#define KEY_CLEAN_SINGLE_5	KEY_SHIFT_CYAN
#define KEY_CLEAN_SINGLE_6	KEY_SHIFT_MAGENTA
//#define KEY_CLEAN_SINGLE_MANUAL (KEY_COMPOSE_PLUS+3)
#endif

//For PG Key board
//Singal Clean=PK1/PK2/PK3/PK4=CN2:41/43/45/47 = VD16/VD17/VD18/VD19 = GPD8/9/10/11 = C/M/Y/K
//Other seven keys: 
//0: LEFT	=CN10: 1	= DB0 = CN2:21	= VD8	= GPD0
//1: RIGHT	=CN10: 2	= DB1 = CN2:23	= VD9	= GPD1
//2: UP		=CN10: 3	= DB2 = CN2:25	= VD10	= GPD2
//3: DOWN	=CN10: 4	= DB3 = CN2:27	= VD11	= GPD3
//4: PAUSE	=CN10: 9	= DB4 = CN2:29	= VD12	= GPD4
//5: PURGE	=CN10: 11	= DB5 = CN2:31	= VD13	= GPD5
//6: ESC	=CN10: 13	= DB6 = CN2:33	= VD14	= GPD6

#endif

#endif
