#include <dwgpio.h>

#define AT91C_BASE_PIOA	DW_BASE_PIOA
#define AT91C_BASE_PIOB	DW_BASE_PIOB
#define AT91C_BASE_PIOC	DW_BASE_PIOC
#define AT91C_BASE_PIOD	DW_BASE_PIOD
#define AT91C_BASE_PIOE	DW_BASE_PIOE
#define AT91C_ID_PIOA	DW_ID_PIOA
#define AT91C_ID_PIOB	DW_ID_PIOB
#define AT91C_ID_PIOC	DW_ID_PIOC
#define AT91C_ID_PIOD	DW_ID_PIOD
#define AT91C_ID_PIOE	DW_ID_PIOE
#define AT91C_ID_PIOD_E	DW_ID_PIOE
